version: '3.0'

services:
  final:
    build: .
    image: final:v2
    ports:
      - "3000:3000"
    links:
      - redis
      - mongo
    networks:
      - net
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - net
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - net
networks: 
    net: 
        driver: bridge     